### PR TITLE
Update and migrate all deps

### PR DESCRIPTION
**Pull request by pronebird**
- Updated all deps
- Updated macOS app lifecycle management (e.g. quit on cmd+q and reopen window if user closed it and then clicked on app icon in dock)
- Added `transform-decorators-legacy` to support decorators
- Added `react` preset for JSX
- Quit node process upon electron termination.

Notes:
Haven't sorted packager yet.

### CODE REVIEW

**Comment by jschr** [comment]
hey @pronebird this looks great. 

I haven't been up to date with electron for the past couple months, but am hoping to get back into soon. I'd gladly add you as a collaborator if you're interested!

**Comment by pronebird** [comment]
@jschr I am still discovering boilerplates. I liked your because it's very minimalistic. But at the moment I am not sure if I will end up using it in production. If that will be the case then I could help to maintain it. :-)

**Comment by jschr** [comment]
I'm not using it in production either at the moment :) I added you as a collaborator since you probably have a better grasp of election then I do right now but there's no obligation on your part! By all means you are welcome to just remove yourself as well. 

 I still hope to get packager working again sometime when I get some time to work on this again.

**Comment by pronebird** [comment]
Great! Thanks a lot!

**Pull request merged**
