### PR TITLE
Added react-router + redux-localstorage

### PR DESCRIPTION
**Pull request by pronebird**
Hi,

I've added react-router and redux-localstorage. 

Local storage was primarily added to workaround the issue of preserving redux state between reloads that are currently done via browser-sync. 

Thoughts/comments?

p.s: will squash before merge.

### CODE REVIEW

**Comment by jschr** [comment]
Changes look good, merge at will! 👍

**Comment by pronebird** [comment]
@jschr tried redux-persist but had a warning when calling `autoHydrate`, described here: https://github.com/michaelcontento/redux-storage/issues/121

I don't have time to investigate this and I think this can be tackled in future, but so far `redux-localstorage` works fine and requires minimum configuration.

**Comment by jschr** [comment]
I haven't used redux-storage before. Just curious, Is that the one that errors or https://github.com/rt2zz/redux-persist?

**Comment by pronebird** [comment]
@jschr yeah I haven't used it either, but I've got the same error when using redux-persist

**Comment by jschr** [comment]
Ah ok, good to know!

I've run into similar errors using redux-persist in a chrome packaged app too.

**Comment by pronebird** [comment]
I think the error we experienced was related to `autoHydrate` when the same URL was pushed twice and apparently react router does not like that. 

I have an assumption that `redux-localstorage` simply swaps entire state from local storage without telling anyone :) which should be alright as long as you handle time travelling in your app (i.e expired sessions etc.. but that's something you have to handle anyway). 

On the other side, this produces certain side effects when used with `syncHistoryWithStore` from `react-redux-router` which gets confused regarding where user comes from and where it goes to.

If I am not entirely crazy this should be legit issue: https://github.com/reactjs/react-router-redux/issues/534

**Pull request merged**
