### PR TITLE
Add travis configuration

### PR DESCRIPTION
**Pull request by pronebird**
Travis is free so why not to add it? This will also give us the assurance that everything we merge passed linter and basic tests we have.

This PR also adds three nice badges to README providing up-to-date status for Travis and dependency freshness. :)

### CODE REVIEW

**Comment by jschr** [comment]
Awesome, great work!

**Comment by pronebird** [comment]
Thanks! I messed up a little copying those badge tags in HTML so I force pushed to master replacing the merged PR with fixed branch. I apologize for messing in repository but the merged README had traces of my personal project :)

**Comment by jschr** [comment]
No worries!

**Comment by jschr** [comment]
Random thought, but if you want to add your personal repo to a "Built with this boilerplate" section in the README I'm all for that! Could be helpful to maintain a list of projects going forward.

**Comment by pronebird** [comment]
@jschr We've just published a pre-release of Mullvad VPN app using this boilerplate

https://github.com/mullvad/mullvadvpn-app

**Comment by jschr** [comment]
@pronebird This looks really awesome, congrats! Really great example of a large electron app. Feel free to link to it in this repo's README :D

**Comment by pronebird** [comment]
@jschr Thanks! I'll update README a little later when I have time. 🎉

**Comment by pronebird** [comment]
I've added a new section to `README.md` – Apps using this boilerplate. Feel free to edit or add more.

**Comment by jschr** [comment]
@pronebird Awesome! Thanks for doing that

**Pull request merged**
