### PR TITLE
update readme to clone the rep with depth=1 option

### PR DESCRIPTION
**Pull request by eladams**

### CODE REVIEW

**Comment by pronebird** [comment]
Hi,

Why is it necessary?

**Comment by jschr** [comment]
> --depth <depth>::
	Create a 'shallow' clone with a history truncated to the
	specified number of revisions.

Reference: https://github.com/git/git/blob/82fba2b9d39163a0c9b7a3a2f35964cbc039e1aa/Documentation/git-clone.txt#L182-L184

Sounds like this would be cleaner solution for starting a new project from this boilerplate without the history.

**Comment by pronebird** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jschr/electron-react-redux-boilerplate/25#-:-KgWbvdTwsb89LMGlPma:bnfp4nl)*

**Comment by pronebird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jschr/electron-react-redux-boilerplate/25)*

**Pull request merged**
