### PR TITLE
Update electron deps

### PR DESCRIPTION
**Pull request by jschr**
Progress on #7. Still a WIP.
- [x] updated electron dependencies
- [ ] convert electron-packager to electron-builder

Having a hard time getting electron-compile to work with electron-packager. A possible better solution could be to remove electron-compile in favour of a basic babel compile script from src -> dist and run electron from dist.

### CODE REVIEW

**Comment by alexemorris** [comment]
Hows it going?

**Comment by jschr** [comment]
Alas I have not had time to revisit this again, sorry about the currently broken state of this repo. 

Have you looked at https://github.com/chentsulin/electron-react-boilerplate? Haven't used it myself but seems popular and has lots of cool features like live-editing.

**Comment by alexemorris** [comment]
Hi, no worries I know the feeling! I was just exploring options. Literally just pulled that repo going to have a look into it, I just liked the small amount of dependencies in your repo. Trying to keep it clean!

**Comment by jschr** [comment]
Ya I hear you, thats why I usually shy away from boilerplates (ah the irony) but it does looks pretty cool! I haven't been using electron lately hence the inactivity on this repo. I'll likely be picking it up again in the near future so I'll try get this working again but may involve a rewrite. The goal would still be minimal dependencies!

**Comment by pronebird** [comment]
@jschr https://github.com/jschr/electron-react-redux-boilerplate is pretty good and they have "clean up" script to turn boilerplate into project removing all sample code. But it seems quite HUGE.

**Comment by jschr** [comment]
Closing since https://github.com/jschr/electron-react-redux-boilerplate/pull/9 was merged. Fixing packager is still a todo. A separate PR will be made for it.

**Pull request closed without merging**
