### PR TITLE
Add redux/react extension for chrome

### PR DESCRIPTION
**Pull request by pronebird**
- Added async/await plugin (see https://medium.com/@bluepnume/learn-about-promises-before-you-start-using-async-await-eb148164a9c8#.g4d1g6et5)
- Added redux/react extension for chrome
- Dropped old redux sidebar

Note: Actions panel in redux extension displays crippled dispatch options for redux actions created with `createAction` from `redux-actions`, normally it's able to parse out parameters and provide friendly input, I raised issue at https://github.com/acdlite/redux-actions/issues/186

screenshot 2017-01-30 19 52 21

### CODE REVIEW

**Comment by jschr** [comment]
This is awesome! Been onboard the async/await train for a while now too. The chrome extension is a great addition. 

BTW, if you intend to keep adding awesome features to the this repo I would gladly transfer it over since I'm already feeling guilty for not keeping it up to date.

**Comment by jschr** [comment]
Also, you're welcome to merge this PR and future ones at your leisure!

**Comment by pronebird** [comment]
@jschr it's alright, no need for transfer. I appreciate that you at least follow commits because I need feedback :)

**Comment by jschr** [comment]
Great, that I can do at least. Thanks for the contributions.

**Pull request merged**
